"""Add practice modes and SRS fields

Revision ID: 05ae138127ed
Revises: 87fda9bf7707
Create Date: 2026-05-06 20:55:28.540481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05ae138127ed'
down_revision: Union[str, None] = '87fda9bf7707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_progress', sa.Column('current_mode', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('user_progress', sa.Column('mode_scores', sa.JSON(), nullable=True))
    op.add_column('user_progress', sa.Column('response_times', sa.JSON(), nullable=True))
    op.add_column('user_progress', sa.Column('avg_response_time', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('user_progress', sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_progress', sa.Column('review_interval', sa.Float(), nullable=False, server_default='1.0'))
    op.add_column('user_progress', sa.Column('ease_factor', sa.Float(), nullable=False, server_default='2.5'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_progress', 'ease_factor')
    op.drop_column('user_progress', 'review_interval')
    op.drop_column('user_progress', 'next_review_at')
    op.drop_column('user_progress', 'avg_response_time')
    op.drop_column('user_progress', 'response_times')
    op.drop_column('user_progress', 'mode_scores')
    op.drop_column('user_progress', 'current_mode')
    # ### end Alembic commands ###
