"""Add user gamification fields

Revision ID: 667e67610e1c
Revises: 05ae138127ed
Create Date: 2026-05-06 21:07:18.911999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '667e67610e1c'
down_revision: Union[str, None] = '05ae138127ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('streak_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('last_streak_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('daily_goal_count', sa.Integer(), nullable=False, server_default='5'))
    op.add_column('users', sa.Column('total_xp', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_xp')
    op.drop_column('users', 'daily_goal_count')
    op.drop_column('users', 'last_streak_date')
    op.drop_column('users', 'streak_count')
    # ### end Alembic commands ###
