"""Add mastery fields to user_progress

Revision ID: 87fda9bf7707
Revises: 742044434ecf
Create Date: 2026-05-06 20:11:21.948959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87fda9bf7707'
down_revision: Union[str, None] = '742044434ecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_progress', sa.Column('best_score', sa.Float(), nullable=False, server_default='0'))
    op.add_column('user_progress', sa.Column('streak_perfect', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user_progress', sa.Column('mastery_level', sa.Float(), nullable=False, server_default='0'))
    op.add_column('user_progress', sa.Column('scores_history', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_progress', 'scores_history')
    op.drop_column('user_progress', 'mastery_level')
    op.drop_column('user_progress', 'streak_perfect')
    op.drop_column('user_progress', 'best_score')
    # ### end Alembic commands ###
